/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdFlowRouteImport } from './routes/jobs.$jobId.flow'
import { Route as JobsJobIdEvidenceRouteImport } from './routes/jobs.$jobId.evidence'
import { Route as JobsJobIdCloseRouteImport } from './routes/jobs.$jobId.close'
import { Route as JobsJobIdArriveRouteImport } from './routes/jobs.$jobId.arrive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdFlowRoute = JobsJobIdFlowRouteImport.update({
  id: '/jobs/$jobId/flow',
  path: '/jobs/$jobId/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdEvidenceRoute = JobsJobIdEvidenceRouteImport.update({
  id: '/jobs/$jobId/evidence',
  path: '/jobs/$jobId/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdCloseRoute = JobsJobIdCloseRouteImport.update({
  id: '/jobs/$jobId/close',
  path: '/jobs/$jobId/close',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdArriveRoute = JobsJobIdArriveRouteImport.update({
  id: '/jobs/$jobId/arrive',
  path: '/jobs/$jobId/arrive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs/$jobId/arrive': typeof JobsJobIdArriveRoute
  '/jobs/$jobId/close': typeof JobsJobIdCloseRoute
  '/jobs/$jobId/evidence': typeof JobsJobIdEvidenceRoute
  '/jobs/$jobId/flow': typeof JobsJobIdFlowRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs/$jobId/arrive': typeof JobsJobIdArriveRoute
  '/jobs/$jobId/close': typeof JobsJobIdCloseRoute
  '/jobs/$jobId/evidence': typeof JobsJobIdEvidenceRoute
  '/jobs/$jobId/flow': typeof JobsJobIdFlowRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs/$jobId/arrive': typeof JobsJobIdArriveRoute
  '/jobs/$jobId/close': typeof JobsJobIdCloseRoute
  '/jobs/$jobId/evidence': typeof JobsJobIdEvidenceRoute
  '/jobs/$jobId/flow': typeof JobsJobIdFlowRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs/$jobId/arrive'
    | '/jobs/$jobId/close'
    | '/jobs/$jobId/evidence'
    | '/jobs/$jobId/flow'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs/$jobId/arrive'
    | '/jobs/$jobId/close'
    | '/jobs/$jobId/evidence'
    | '/jobs/$jobId/flow'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/jobs/$jobId/arrive'
    | '/jobs/$jobId/close'
    | '/jobs/$jobId/evidence'
    | '/jobs/$jobId/flow'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsJobIdArriveRoute: typeof JobsJobIdArriveRoute
  JobsJobIdCloseRoute: typeof JobsJobIdCloseRoute
  JobsJobIdEvidenceRoute: typeof JobsJobIdEvidenceRoute
  JobsJobIdFlowRoute: typeof JobsJobIdFlowRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/flow': {
      id: '/jobs/$jobId/flow'
      path: '/jobs/$jobId/flow'
      fullPath: '/jobs/$jobId/flow'
      preLoaderRoute: typeof JobsJobIdFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/evidence': {
      id: '/jobs/$jobId/evidence'
      path: '/jobs/$jobId/evidence'
      fullPath: '/jobs/$jobId/evidence'
      preLoaderRoute: typeof JobsJobIdEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/close': {
      id: '/jobs/$jobId/close'
      path: '/jobs/$jobId/close'
      fullPath: '/jobs/$jobId/close'
      preLoaderRoute: typeof JobsJobIdCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/arrive': {
      id: '/jobs/$jobId/arrive'
      path: '/jobs/$jobId/arrive'
      fullPath: '/jobs/$jobId/arrive'
      preLoaderRoute: typeof JobsJobIdArriveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsJobIdArriveRoute: JobsJobIdArriveRoute,
  JobsJobIdCloseRoute: JobsJobIdCloseRoute,
  JobsJobIdEvidenceRoute: JobsJobIdEvidenceRoute,
  JobsJobIdFlowRoute: JobsJobIdFlowRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
